version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: kiradb
      MYSQL_ROOT_PASSWORD: gasWorp12
    ports:
      - "3306:3306"

  web:
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_DATABASE: kiradb
      MYSQL_PASSWORD: gasWorp12
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db